name: lint

on:
  push:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    env:
      tf_version: latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.tf_version }}

      - name: terraform format
        run: ./scripts/lint.sh
