name: review
on:
  pull_request:
jobs:
  review:
    name: tfsec PR validator
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Run tfsec with reviewdog
        uses: reviewdog/action-tfsec@v1.15.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: terraform
          level: info
          reporter: github-pr-review
          fail_on_error: true
          tfsec_flags: "--minimum-severity HIGH"